export const cases = [
  {
    id: 0,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 1,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 2,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 3,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 4,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 5,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 6,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 7,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 8,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 9,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
];

export const HearingDetail = [
  {
    Id : 0 ,
    CaseId: 54354,
    HearingDate:"23 Oct 2023",
    HearingDetails:"This is details of nothing...",
  },
  {
    Id : 1 ,
    CaseId: 54374,
    HearingDate:"26 Oct 2023",
    HearingDetails:"This is details of something...",
  },
]
export const Evidence = [
  {
    Id:0,
    CaseId:54374,
    EvidenceDescription:"This is details of something ...",
    Image:"user-36-08.jpg",
  },
  {
    Id:1,
    CaseId:51974,
    EvidenceDescription:"This is details of something ...",
    Image:"user-36-08.jpg",
  }
]