export const cases = [
  {
    id: 0,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 1,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 2,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 3,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 4,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 5,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 6,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 7,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 8,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
  {
    id: 9,
    cnrNumber: 125202,
    dateFile: "23 Oct 2023",
    caseType: "Criminal",
    advocate: "Ramesh Bhai",
    attoryAdvocate: "Suresh Bhai",
    defendant: "Sandeep Bhai",
    petttioer: "Mahesh Bhai",
    judge: "Nilesh Bhai",
    caseStatus: "Pending",
  },
];
